stages:
 - build
 - test

build:
  stage: build
  script:
    - cd back-end;
    - ./gradlew build -x test
    - ./gradlew.bat --stop


test:
  stage: test
  script:
    - cd back-end;
    - ./gradlew test
    - ./gradlew.bat --stop
